name: qnotero
version: 2.2.0
summary: Standalone sidekick to Zotero reference manager.
description: |
 Qnotero provides lightning quick access to your Zotero references,
  searching through your references by author, year of publication, and DOI
base: core18
confinement: devmode

parts:
  qnotero:
    plugin: python
    source: https://github.com/ealbiter/qnotero.git
    stage-packages:
      - python3-pyqt5
      - python3-sip
    build-packages:
      - python3-distutils

apps:
  qnotero:
    command: bin/qnotero
    plugs:
      - home