name: qnotero
version: 2.2.0
summary: Standalone sidekick to Zotero reference manager.
description: |
 Qnotero provides lightning quick access to your Zotero references,
  searching through your references by author, year of publication, and DOI
base: core18
confinement: strict

parts:
  qnotero:
    plugin: python
    source: https://github.com/ealbiter/qnotero.git
    stage-packages:
      - python3-pyqt5
    build-packages:
      - python3-setuptools

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    #- qt5-gtk-platformtheme

apps:
  qnotero:
    desktop: lib/python3.6/site-packages/usr/share/applications/qnotero.desktop
    command: bin/qnotero
    plugs:
      - network-bind
      - home

layout:
  /usr/share/qnotero:
    symlink: $SNAP/lib/python3.6/site-packages/usr/share/qnotero