name: qnotero
title: Qnotero
version: '2.2.1'
summary: Standalone sidekick to Zotero reference manager.
description: |
 Qnotero provides lightning-quick access to your Zotero references,
  searching through your references by author, year of publication, and DOI.
base: core18
confinement: strict
grade: stable

plugs:
  zoterodata:
    interface: content
    content: writable-data
    target: $SNAP_USER_COMMON/Zotero

parts:
  qnotero:
    plugin: python
    source: https://github.com/ealbiter/qnotero.git
    override-pull: |
       snapcraftctl pull
       sed -i.bak -e 's|Icon=/usr/share/qnotero/resources/light/qnotero.png|Icon=lib/python3.6/site-packages/usr/share/qnotero/resources/light/qnotero.png|g' resources/Linux/qnotero.desktop
    stage-packages:
      - python3-pyqt5
    build-packages:
      - python3-setuptools

apps:
  qnotero:
    desktop: lib/python3.6/site-packages/usr/share/applications/qnotero.desktop
    extensions:
      - kde-neon
    command: bin/qnotero
    plugs:
      - network-bind
      - system-observe
      - home
      - unity7

layout:
  /usr/share/qnotero:
    symlink: $SNAP/lib/python3.6/site-packages/usr/share/qnotero